# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.kernelParams = [
    "pcie_aspm=force"
  ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/2a115505-f6ab-403f-a1c3-ed46406ebaf6";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/EBEA-B5B0";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };
  
  # MEDIA RAID5 BTRFS
  fileSystems."/srv" = {
  device = "UUID=a7258f04-8147-4056-88df-cdeffc2d5432";
  fsType = "btrfs";
  options = [
      "subvol=library"
      "compress=zstd"
      "noatime"
    ];
  };
  fileSystems."/srv/.snapshots" = {
    device = "UUID=a7258f04-8147-4056-88df-cdeffc2d5432";
    fsType = "btrfs";
    options = [
      "subvol=snapshots"
      "noatime"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
