# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-68f4f599-fc7d-4eaf-9015-2a6da17a72aa";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-68f4f599-fc7d-4eaf-9015-2a6da17a72aa".device =
    "/dev/disk/by-uuid/68f4f599-fc7d-4eaf-9015-2a6da17a72aa";
  boot.initrd.luks.devices."luks-fa5e8709-1067-4b42-b848-ab242e183e02".device =
    "/dev/disk/by-uuid/fa5e8709-1067-4b42-b848-ab242e183e02";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/E250-4F92";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-fa5e8709-1067-4b42-b848-ab242e183e02"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
